version: '3.3'
volumes:
    persistant-data:
      
services:
    # Define Universe Container
    universe-server:
        container_name: universe-server
        build: ./universe
        # These ports a exposed to the local host.  If they are in use
        # you need to change these.  If Universe is loaded locally
        # you will need to change 31438:31438 to 31439:31438
        ports:
            - "20022:22"
            - "31438:31438"
        # Mounted volumes. 
        # shared-data mounts the local project shared-data directory making it easy to share files
        # persistant-data is a Volume storage and is where your account/dynamic work should be done
        volumes:
            - "./shared-data:/shared-data"
            - "persistant-data:/data"
 